Header
petekostrytsya/DevHunt pull request #12
Opened 2023-01-22 10:42 UTC by petekostrytsya

2023-01-22 10:44 UTC, petekostrytsya commented
Перевірте будь ласка, чи відкриє в вас

2023-01-22 11:39 UTC, PetroShutak commented
не відкриває

2023-01-22 15:35 UTC, barkode approved these changes
Так відкривається

2023-01-22 16:49 UTC, PetroShutak approved these changes

2023-01-22 19:25 UTC, barkode requested changes
Дороби трішечки. Потрібно щоб воно було у контейнері, а не розтягнуто на весь екран. Також стилі втрачаються на 480 пікселях.

2023-01-23 10:50 UTC, barkode commented
Треба відцентрувати.

2023-01-23 11:18 UTC, barkode approved these changes

2023-01-23 11:19 UTC, barkode commented
Я замерджу цю гілку. Сильно воно не ламає, зате буде видно як воно.

2023-01-23 11:20 UTC, merged