Feature/advantages
petekostrytsya/DevHunt pull request #20
Opened 2023-01-22 20:57 UTC by AlexanderPyatnitsky

2023-01-23 15:47 UTC, petekostrytsya requested changes
Немає контенера на 480, підтягується не та картинка

2023-01-24 00:41 UTC, barkode requested changes
Виправи будь ласка всі помилки.

2023-01-24 00:41 UTC, barkode commented on src/sass/_advantages.scss
> +.cow-icon {
відсутня назва секції у класі.

2023-01-24 00:41 UTC, barkode commented on src/partials/advantages.html
> +  <!-- <div class="container"> -->
Все повинно бути у контейнері.

2023-01-24 00:41 UTC, barkode commented on src/partials/advantages.html
> +  <!-- </div> -->
Повинно бути у контейнері

2023-01-24 00:41 UTC, barkode commented on src/sass/_advantages.scss
> +* {
Не повинно бути цього у файлі. Воно є глобально. З 1 по 12 строку.

2023-01-24 00:41 UTC, barkode commented on src/sass/_advantages.scss
> +}
Не повинно бути цього у файлі. Воно є глобально. З 1 по 12 строку.

2023-01-24 01:26 UTC, barkode commented
Виправив можно мержити.

2023-01-24 01:27 UTC, barkode approved these changes

2023-01-24 09:39 UTC, petekostrytsya approved these changes

2023-01-24 09:39 UTC, merged