Hero
petekostrytsya/DevHunt pull request #4
Opened 2023-01-20 14:33 UTC by AndriiZlt

2023-01-20 15:30 UTC, barkode requested changes

2023-01-20 15:30 UTC, barkode commented on src/partials/hero.html
> +<!DOCTYPE html>
Ця строка не потрібна. Вона вже є у головному файлі index.html. Просто видали її.

2023-01-20 15:30 UTC, barkode commented on src/partials/hero.html
> +<html lang="en">
Ця строка не потрібна. Вона вже є у головному файлі index.html. Просто видали її.

2023-01-20 15:30 UTC, barkode commented on src/sass/_hero.scss
> +  font-weight: 400;
Не потрібно вказувати, він 400 weight іде по замовчуванню

2023-01-20 15:30 UTC, barkode commented on src/sass/_hero.scss
> +  font-family: 'Seymour One';
Вкажи замість назви шрифта його змінну   font-family: var(--secondary-font); На дошці трело в нас є змінна для шрифтів.
для цього шрифта --secondary-font: 'Seymour One', sans-serif;

2023-01-20 15:30 UTC, barkode commented on src/partials/hero.html
> +  <head>
Ця строка не потрібна. Вона вже є у головному файлі index.html. Просто видали її.

2023-01-20 15:30 UTC, barkode commented on src/partials/hero.html
> +    <meta charset="UTF-8" />
Ця строка не потрібна. Вона вже є у головному файлі index.html. Просто видали її.

2023-01-20 15:30 UTC, barkode commented on src/partials/hero.html
> +    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
Ця строка не потрібна. Вона вже є у головному файлі index.html. Просто видали її.

2023-01-20 15:30 UTC, barkode commented on src/partials/hero.html
> +  </body>
Ця строка не потрібна. Вона вже є у головному файлі index.html. Просто видали її.

2023-01-20 15:30 UTC, barkode commented on src/partials/hero.html
> +</html>
Ця строка не потрібна. Вона вже є у головному файлі index.html. Просто видали її.

2023-01-20 15:30 UTC, barkode commented on src/partials/hero.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
Ця строка не потрібна. Вона вже є у головному файлі index.html. Просто видали її.

2023-01-20 15:30 UTC, barkode commented on src/partials/hero.html
> +    <title>Document</title>
Ця строка не потрібна. Вона вже є у головному файлі index.html. Просто видали її.

2023-01-20 15:30 UTC, barkode commented on src/partials/hero.html
> +  </head>
Ця строка не потрібна. Вона вже є у головному файлі index.html. Просто видали її.

2023-01-20 15:30 UTC, barkode commented on src/partials/hero.html
> +  <body>
Ця строка не потрібна. Вона вже є у головному файлі index.html. Просто видали її.

2023-01-20 15:30 UTC, barkode commented on src/sass/_hero.scss
> +  color: var(--btn-studio-text);
У нас такої змінної для кольору не має. Зміни просто на потрібний колір.

2023-01-20 15:30 UTC, barkode commented on src/sass/_hero.scss
> +  background-color: var(--btn-studio-background);
Такої змінної для кольору теж нема. Зміни просто на потрібний колір.

2023-01-20 15:30 UTC, barkode commented on src/sass/_hero.scss
> +  background-color: #84a178;
Цей колір у нас прописаний для секціі загальний. Просто видали атрибут background-color: #84a178;

2023-01-20 15:40 UTC, petekostrytsya requested changes
Повиправляй будь ласка

2023-01-20 15:40 UTC, petekostrytsya commented on src/partials/hero.html
> +<!DOCTYPE html>
Прибрати від 1 до 11 строчки

2023-01-20 15:40 UTC, petekostrytsya commented on src/partials/hero.html
> +          <a href="#advantages" class="btn-how">How it’s made?</a>
теж саме

2023-01-20 15:40 UTC, petekostrytsya commented on src/partials/hero.html
> +            src="../images/hero/ice-cream 480.svg"
./imeges (повинна бути одна крапка, бо img та partials знаходяться на одному рівні)

2023-01-20 15:40 UTC, petekostrytsya commented on src/partials/hero.html
> +            src="../images/hero/left 480.svg"
теж саме

2023-01-20 15:40 UTC, petekostrytsya commented on src/partials/hero.html
> +          <img src="../images/hero/Arrow.svg" alt="Arrow" class="arrow" />
43, 48, 53, 58, 62 рядки убрать точку

2023-01-20 15:40 UTC, petekostrytsya commented on src/sass/_hero.scss
> +
не  бачу медиа правила для мобілки

2023-01-20 15:52 UTC, AndriiZlt commented on src/sass/_hero.scss
> +
Все правила написаны для мобилки и переписаны для Tablet и Desktop.

2023-01-20 16:05 UTC, AndriiZlt commented on src/sass/_hero.scss
> +  background-color: var(--btn-studio-background);
Это какой то баг от copy-paste. Проверил, у меня в коде такого сейчас нет.

2023-01-20 16:05 UTC, AndriiZlt commented on src/sass/_hero.scss
> +  background-color: #84a178;
+

2023-01-20 16:05 UTC, AndriiZlt commented on src/partials/hero.html
> +  <body>
+

2023-01-20 16:06 UTC, AndriiZlt commented on src/partials/hero.html
> +  </head>
+

2023-01-20 16:06 UTC, AndriiZlt commented on src/partials/hero.html
> +  <head>
+

2023-01-20 16:06 UTC, AndriiZlt commented
Исправил все

2023-01-20 16:07 UTC, AndriiZlt commented on src/partials/hero.html
> +<html lang="en">
ok

2023-01-20 16:07 UTC, AndriiZlt commented on src/sass/_hero.scss
> +  font-weight: 400;
ok

2023-01-20 16:07 UTC, AndriiZlt commented on src/partials/hero.html
> +<!DOCTYPE html>
ok

2023-01-20 16:08 UTC, AndriiZlt commented on src/sass/_hero.scss
> +  color: var(--btn-studio-text);
ok

2023-01-20 16:08 UTC, AndriiZlt commented on src/partials/hero.html
> +<!DOCTYPE html>
ok

2023-01-20 16:09 UTC, AndriiZlt commented on src/partials/hero.html
> +            src="../images/hero/ice-cream 480.svg"
ok

2023-01-20 16:12 UTC, barkode requested changes
Можешь додати до назви своїх классів спочатку назву твоеї секціі. Наприклад hero-arrow. Це щоб ми потім не заплутались, якщо хтось назве клас як і ти назвав. Дякую.

2023-01-20 16:12 UTC, barkode commented on src/partials/hero.html
> +      <img src="./images/hero/left 480.svg" alt="Dots" class="krapki-left" />
Підкорегуй назву класу на hero-krapki-left

2023-01-20 16:12 UTC, barkode commented on src/partials/hero.html
> +      <img src="./images/hero/right 480.svg" alt="Dots" class="krapki-right" />
Підкорегуй назву класу на hero-krapki-right

2023-01-20 16:12 UTC, barkode commented on src/partials/hero.html
> +        class="plate"
Підкорегуй назву класу на hero-plate

2023-01-20 16:12 UTC, barkode commented on src/partials/hero.html
> +      <img src="./images/hero/left-tablet.svg" alt="Dots" class="left-tablet" />
Підкорегуй назву класу на hero-left-tablet

2023-01-20 16:12 UTC, barkode commented on src/partials/hero.html
> +      <img src="./images/hero/Arrow.svg" alt="Arrow" class="arrow" />
Підкорегуй назву класу на hero-arrow

2023-01-20 16:12 UTC, barkode commented on src/partials/hero.html
> +        class="all-dots"
Підкорегуй назву класу на hero-dots

2023-01-20 16:12 UTC, barkode commented on src/partials/hero.html
> +      <a href="" class="btn-how">How it’s made?</a>
Підкорегуй назву класу на hero-btn-now

2023-01-20 16:12 UTC, barkode commented on src/partials/hero.html
> +      <a href="" class="btn-products">Products</a>
Підкорегуй назву класу на hero-btn-product

2023-01-20 16:12 UTC, barkode commented on src/partials/hero.html
> +          <p class="text-info">food trucks</p>
Підкорегуй назву класу на hero-text-info

2023-01-20 16:12 UTC, barkode commented on src/partials/hero.html
> +          <p class="title-info">23</p>
Підкорегуй назву класу на hero-title-info

2023-01-20 16:12 UTC, barkode commented on src/partials/hero.html
> +          <p class="text-info">cafes</p>
Підкорегуй назву класу на hero-text-info

2023-01-20 16:12 UTC, barkode commented on src/partials/hero.html
> +          <p class="title-info">16</p>
Підкорегуй назву класу на hero-title-info

2023-01-20 16:12 UTC, barkode commented on src/partials/hero.html
> +      <ul class="list info">
Підкорегуй назву класу на hero-list hero-info

2023-01-20 16:51 UTC, AndriiZlt commented
Зробил

2023-01-21 05:24 UTC, AndriiZlt commented
1. Responsive image attached
2. Sprite SVG attached
3. Bugs fixed

2023-01-21 09:21 UTC, barkode approved these changes

2023-01-21 11:22 UTC, barkode approved these changes

2023-01-21 16:00 UTC, barkode commented
Там у тебе ломається дизайн на 768 та 480.

2023-01-21 16:11 UTC, AndriiZlt commented
Я переробив реалізацію зображень, щоб переконатися, що вона працює добре.

2023-01-21 19:07 UTC, petekostrytsya approved these changes

2023-01-21 19:21 UTC, merged