Gallery+customers
petekostrytsya/DevHunt pull request #6
Opened 2023-01-21 09:23 UTC by arhistratig65

html+css

2023-01-21 11:21 UTC, barkode requested changes

2023-01-21 11:21 UTC, barkode commented on src/sass/_gallery.scss
> +    h1,
З 1 по 41 рядок треба видалити, воно є у основному файлі ресету.

2023-01-21 11:21 UTC, barkode commented on src/sass/_gallery.scss
> +    }
З 1 по 41 рядок треба видалити, воно є у основному файлі ресету.

2023-01-21 11:21 UTC, barkode commented on src/partials/gallery.html
> +<!DOCTYPE html>
З 1 по 16 рядок треба видалити, воно є у основному файлі ресету.

2023-01-21 11:21 UTC, barkode commented on src/partials/gallery.html
> +</head>
З 1 по 16 рядок треба видалити, воно є у основному файлі ресету.

2023-01-21 11:21 UTC, barkode commented on src/partials/contacts.html
> +h1,
Можливо файл треба перейменувати у _contacts.scss.

2023-01-23 20:09 UTC, barkode approved these changes

2023-01-23 20:11 UTC, petekostrytsya approved these changes

2023-01-23 20:15 UTC, merged