Origin/about
petekostrytsya/DevHunt pull request #7
Opened 2023-01-21 10:29 UTC by Yuliia-Karas

Section about is ready

2023-01-21 11:03 UTC, barkode approved these changes

2023-01-21 18:29 UTC, petekostrytsya requested changes
Бекграунд на десктопі

2023-01-21 18:29 UTC, petekostrytsya commented on src/sass/_about.scss
> +    background-image: url(../images/background/about-bg/about-picture-bg-480.png);
Виправити бекграунд на десктопі

2023-01-22 08:52 UTC, Yuliia-Karas commented on src/sass/_about.scss
> +    background-image: url(../images/background/about-bg/about-picture-bg-480.png);
all done

2023-01-22 09:00 UTC, petekostrytsya approved these changes

2023-01-22 09:00 UTC, merged